spring:
  application:
    name: CacheMeasuring
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: system
    password: oracle
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect

  cache:
    type: simple

management:
  endpoints:
    web:
      exposure:
        include: metrics